language: python
python:
  - "3.7"
install:
  - pip3 install homeassistant
script:
  # - ./set-config.sh tank
  # - hass -c . --script check_config
  - ./set-config.sh super
  - hass -c . --script check_config
  - ./set-config.sh super pt
  - hass -c . --script check_config
  - ./set-config.sh pump
  - hass -c . --script check_config
- ./set-config.sh pump pt
  - hass -c . --script check_config
before_install:
  - mv secrets-dummy.yaml secrets.yaml
