language: python
python:
  - "3.7"
install:
  - pip3 install homeassistant
script:
  - ./set-config.sh castle
  - hass -c . --script check_config
  - ./set-config.sh super
  - hass -c . --script check_config
#before_install:
#  - mv dummy_secrets.yaml secrets.yaml
