title: Supervisor Panel
views:
  - title: Home
    cards:
      - type: vertical-stack
        cards:
          - type: sensor
            entity: sensor.tank_water_level
            name: Tank Capacity
            #line_color: "#3498db"
            accuracy: 50
            height: 150
            detail: 2
            graph: line
            unit: "%"
          - type: history-graph
            title: 'Analog'
            refresh_interval: 60
            entities:
              - entity: sensor.pump_ads1x15_0
                name: A0
              - entity: sensor.pump_ads1x15_1
                name: A1
          - type: history-graph
            title: 'Temperature'
            refresh_interval: 60
            entities:
              - entity: sensor.pump_htu21d_temperature
                name: Pump
              - entity: sensor.tank_htu21d_temperature
                name: Tank
              - entity: sensor.super_htu21d_temperature
                name: Super
          - type: history-graph
            title: 'Humidity'
            refresh_interval: 60
            entities:
              - entity: sensor.pump_htu21d_humidity
                name: Pump
              - entity: sensor.tank_htu21d_humidity
                name: Tank
              - entity: sensor.super_htu21d_humidity
                name: Super
          - type: history-graph
            title: 'Luminance'
            refresh_interval: 60
            entities:
              - entity: sensor.pump_bh1750
                name: Pump
              - entity: sensor.tank_bh1750
                name: Tank
              - entity: sensor.super_bh1750
                name: Super
      - type: vertical-stack
        cards:
          - type: history-graph
            title: 'Delta-Temperature'
            refresh_interval: 60
            entities:
              - entity: sensor.pump_delta_temperature
                name: Pump
              - entity: sensor.tank_delta_temperature
                name: Tank
          - type: entities
            title: Supervisor
            show_header_toggle: false
            entities:
              - sensor.super_htu21d_temperature
              - sensor.super_htu21d_humidity
              - sensor.super_bh1750
          - type: entities
            title: Tank
            show_header_toggle: false
            entities:
              #- sensor.tank_delta_temperature
              - sensor.tank_htu21d_temperature
              #- sensor.tank_delta_humidity
              - sensor.tank_htu21d_humidity
              - sensor.tank_bh1750
              - sensor.tank_vl53l1x
              #- sensor.tank_gpu_temperature
          - type: entities
            title: Pump
            show_header_toggle: false
            entities:
              #- sensor.pump_delta_temperature
              - sensor.pump_htu21d_temperature
              #- sensor.pump_delta_humidity
              - sensor.pump_htu21d_humidity
              - sensor.pump_bh1750
              #- sensor.pump_gpu_temperature
      - type: vertical-stack
        cards:
          - type: history-graph
            title: 'Delta-Humidity'
            refresh_interval: 60
            entities:
              - entity: sensor.pump_delta_humidity
                name: Pump
              - entity: sensor.tank_delta_humidity
                name: Tank
          - type: entities
            title: Climate
            show_header_toggle: false
            entities:
              - sun.sun
              - sensor.yr_symbol
          - type: gauge
            title: CPU
            name: CPU
            show_header_toggle: true
            entity: sensor.processor_use
            severity:
              green: 0
              yellow: 50
              red: 90
          - type: entities
            title: Computer
            show_header_toggle: false
            entities:
              - sensor.memory_free
              # - sensor.network_in_eth0
              # - sensor.network_out_eth0
              - sensor.super_network
              - sensor.disk_use_percent
              - sensor.super_gpu_temperature

      #- type: entities
      #  title: Zones
      #  show_header_toggle: false
      #  entities:
      #    - zone.bloco_0
      #    - zone.bloco_1
      #    - zone.bloco_2
      #    - zone.bloco_3
      #    - zone.bloco_4
      #    - zone.bloco_5
      #    - zone.castelo
      #    - zone.piscina
