title: Supervisor Panel
views:
  - title: Home
    cards:
#      - type: entities
#        title: Sinalização
#        show_header_toggle: true
#        entities:
#          - light.anavi_light_phat

      - type: vertical-stack
        cards:
          - type: sensor
            entity: sensor.tank_water_level
            name: Tank Capacity
            #line_color: "#3498db"
            accuracy: 50
            height: 150
            detail: 2
            graph: line
            unit: "%"
          - type: history-graph
            title: 'Temperature'
            refresh_interval: 60
            entities:
              - entity: sensor.super_htu21d_temperature
                name: Super
              - entity: sensor.tank_htu21d_temperature
                name: Tank
              - entity: sensor.pump_htu21d_temperature
                name: Pump
          - type: history-graph
            title: 'Humidity'
            refresh_interval: 60
            entities:
              - entity: sensor.super_htu21d_humidity
                name: Super
              - entity: sensor.tank_htu21d_humidity
                name: Tank
              - entity: sensor.pump_htu21d_humidity
                name: Pump
          # - type: history-graph
          #   title: 'Delta temperature'
          #   refresh_interval: 60
          #   entities:
          #     - entity: sensor.tank_delta_temperature
          #       name: Tank
          #     - entity: sensor.pump_delta_temperature
          #       name: Pump
          # - type: history-graph
          #   title: 'Delta humidity'
          #   refresh_interval: 60
          #   entities:
          #     - entity: sensor.tank_delta_humidity
          #       name: Tank
          #     - entity: sensor.pump_delta_humidity
          #       name: Pump
          # - type: sensor
          #   entity: sensor.tank_delta_temperature
          #   name: Tank Delta Temperature
          #   #line_color: "#3498db"
          #   accuracy: 50
          #   height: 150
          #   detail: 2
          #   graph: line
          #   unit: "°C"
          # - type: sensor
          #   entity: sensor.tank_delta_humidity
          #   name: Tank Delta Humidity
          #   #line_color: "#3498db"
          #   accuracy: 50
          #   height: 150
          #   detail: 2
          #   graph: line
          #   unit: "%"
          # - type: sensor
          #   entity: sensor.pump_delta_temperature
          #   name: Pump Delta Temperature
          #   #line_color: "#3498db"
          #   accuracy: 50
          #   height: 150
          #   detail: 2
          #   graph: line
          #   unit: "°C"
          # - type: sensor
          #   entity: sensor.pump_delta_humidity
          #   name: Pump Delta Humidity
          #   #line_color: "#3498db"
          #   accuracy: 50
          #   height: 150
          #   detail: 2
          #   graph: line
          #   unit: "%"
      - type: vertical-stack
        cards:
          - type: history-graph
            title: 'Delta-Temperature'
            refresh_interval: 60
            entities:
              - entity: sensor.tank_delta_temperature
                name: Tank
              - entity: sensor.pump_delta_temperature
                name: Pump
          - type: entities
            title: Supervisor
            show_header_toggle: false
            entities:
              - sensor.super_htu21d_temperature
              - sensor.super_htu21d_humidity
              - sensor.super_bh1750
          - type: entities
            title: Tank
            show_header_toggle: false
            entities:
              #- sensor.tank_delta_temperature
              - sensor.tank_htu21d_temperature
              #- sensor.tank_delta_humidity
              - sensor.tank_htu21d_humidity
              - sensor.tank_bh1750
              - sensor.tank_vl53l1x
              #- sensor.tank_gpu_temperature
          - type: entities
            title: Pump
            show_header_toggle: false
            entities:
              #- sensor.pump_delta_temperature
              - sensor.pump_htu21d_temperature
              #- sensor.pump_delta_humidity
              - sensor.pump_htu21d_humidity
              - sensor.pump_bh1750
              #- sensor.pump_gpu_temperature
      - type: vertical-stack
        cards:
          - type: history-graph
            title: 'Delta-Humidity'
            refresh_interval: 60
            entities:
              - entity: sensor.tank_delta_humidity
                name: Tank
              - entity: sensor.pump_delta_humidity
                name: Pump
          - type: entities
            title: Climate
            show_header_toggle: false
            entities:
              - sun.sun
              - sensor.yr_symbol
          - type: gauge
            title: CPU
            name: CPU
            show_header_toggle: true
            entity: sensor.processor_use
            severity:
              green: 0
              yellow: 50
              red: 90
          - type: entities
            title: Raspberry Pi
            show_header_toggle: false
            entities:
              - sensor.memory_free
              # - sensor.network_in_eth0
              # - sensor.network_out_eth0
              - sensor.super_network
              - sensor.disk_use_percent
              - sensor.super_gpu_temperature

      #- type: entities
      #  title: Zones
      #  show_header_toggle: false
      #  entities:
      #    - zone.bloco_0
      #    - zone.bloco_1
      #    - zone.bloco_2
      #    - zone.bloco_3
      #    - zone.bloco_4
      #    - zone.bloco_5
      #    - zone.castelo
      #    - zone.piscina
