title: Caixa d'Água do Castelo
views:
  - title: Home
    cards:
      - type: vertical-stack
        cards:
          - type: sensor
            entity: sensor.tank_water_level_mm
            name: Linha dÁgua
            #line_color: "#3498db"
            accuracy: 50
            height: 150
            detail: 2
            graph: line
            unit: "mm"
          # - type: history-graph
          #   title: 'Capacidade'
          #   refresh_interval: 60
          #   entities:
          #     - entity: sensor.tank_water_level
          #       name: Castelo
          # - type: sensor
          #   entity: sensor.tank_water_level
          #   name: Capacidade
          #   #line_color: "#3498db"
          #   accuracy: 50
          #   height: 150
          #   detail: 2
          #   graph: line
          #   unit: "%"
          - type: history-graph
            title: 'Linha dÁgua'
            refresh_interval: 60
            entities:
              - entity: sensor.tank_water_level_mm
                name: Castelo

          - type: history-graph
            title: 'Temperatura'
            refresh_interval: 60
            entities:
              - entity: sensor.tank_gpu_temperature
                name: GPU
              - entity: sensor.yr_temperature
                name: Ambiente
              - entity: sensor.tank_htu21d_temperature
                name: Interna

      - type: vertical-stack
        cards:
          - type: entities
            title: Sensores
            show_header_toggle: false
            entities:
              #- sensor.water_level
              #- sensor.tank_water_level_mm
              - sensor.tank_htu21d_temperature
              - sensor.tank_htu21d_humidity
              - sensor.tank_bh1750
              - sensor.tank_vl53l1x
              - sensor.tank_water_level_mm

          - type: gauge
            title: CPU
            name: CPU
            show_header_toggle: true
            entity: sensor.processor_use
            severity:
              green: 0
              yellow: 50
              red: 90

          - type: entities
            title: Computador
            show_header_toggle: false
            entities:
              - sensor.memory_free
              # - sensor.network_in_eth0
              # - sensor.network_out_eth0
              - sensor.tank_network
              - sensor.disk_use_percent
              - sensor.tank_gpu_temperature
              - sensor.tank_throttled
  - title: Gráfico
    id: castelo
    cards:
      - type: iframe
        id: graf1
        url: http://192.168.0.233:3000/d/TQ7LKlzRz/castelo-canoas?orgId=1&from=1569512913700&to=1569534513700&refresh=1m&theme=light
        aspect_ratio: 100%
